#!/usr/bin/env bash
set -e

function die() {
	>&2 echo Fatal: $@
	exit 1
}
[[ "$1" ]] || die Need service name
[[ "$2" ]] || die Need handler
[[ "$3" ]] || die Need port

ciao build -x .

# Start server in background with repl running.
ciao toplevel                           \
	-u "./pl/webapp/webapp.pl"        \
	-e 'use_module(library(concurrency))' \
	-e 'use_module(library(listing))'     \
	-e 'use_module(library(librowser))'   \
	-e "use_module(library($1))"          \
	-e "eng_call(webapp:serve($1:$2, $3), create, create)"
