#!/usr/bin/env bash
set -e

function die() {
	>&2 echo Fatal: $@
	exit 1
}
[[ "$1" ]] || die Need service name
[[ "$2" ]] || die Need port

ciao toplevel                           \
	-u "./pl/webapp/webapp.pl"            \
	-e "use_module(library($1))"          \
	-e "call(webapp:serve($1:handle, $2))"
