#!/usr/bin/env bash
set -e

ciao build $1

# Start server in background with repl running.
ciao toplevel                          \
	-u "./ws/"$1"/cmds/serve.pl"         \
	-e 'use_module(library(concurrency))'\
	-e 'use_module(library(listing))'\
	-e 'use_module(library(librowser))'\
	-e 'eng_call(serve:main, create, create)'
